import LoadableComponent from './../Loadable/index';

export const userRouter: any = [
  {
    path: '/user',
    name: 'user',
    title: 'User',
    component: LoadableComponent(() => import('../../components/Layout/UserLayout')),
    isLayout: true,
    showInMenu: false,
  },
  {
    path: '/user/login',
    name: 'login',
    title: 'LogIn',
    component: LoadableComponent(() => import('../../scenes/Login')),
    showInMenu: false,
  },
];

export const appRouters: any = [
  {
    path: '/',
    exact: true,
    name: 'home',
    permission: '',
    title: 'Home',
    icon: 'home',
    component: LoadableComponent(() => import('../../components/Layout/AppLayout')),
    isLayout: true,
    showInMenu: false,
  },
  {
    path: '/dashboard',
    name: 'dashboard',
    permission: '',
    title: 'Dashboard',
    icon: 'home',
    showInMenu: true,
    component: LoadableComponent(() => import('../../scenes/Dashboard')),
  },
  {
    path: '/users',
    permission: 'Pages.Users',
    title: 'Users',
    name: 'user',
    icon: 'user',
    showInMenu: true,
    component: LoadableComponent(() => import('../../scenes/Users')),
  },
  {
    path: '/roles',
    permission: 'Pages.Roles',
    title: 'Roles',
    name: 'role',
    icon: 'tags',
    showInMenu: true,
    component: LoadableComponent(() => import('../../scenes/Roles')),
  },
  {
    path: '/tenants',
    permission: 'Pages.Tenants',
    title: 'Tenants',
    name: 'tenant',
    icon: 'appstore',
    showInMenu: true,
    component: LoadableComponent(() => import('../../scenes/Tenants')),
  },
  {
    path: '/logout',
    permission: '',
    title: 'Logout',
    name: 'logout',
    icon: 'info-circle',
    showInMenu: false,
    component: LoadableComponent(() => import('../../components/Logout')),
  },
  {
    path: '/exception?:type',
    permission: '',
    title: 'exception',
    name: 'exception',
    icon: 'info-circle',
    showInMenu: false,
    component: LoadableComponent(() => import('../../scenes/Exception')),
  },
  {
    path: '/Blogs',
    permission: '',
    title: 'Blogs',
    name: 'Blogs',
    icon: 'book',
    showInMenu: true,
    component: LoadableComponent(() => import('../../scenes/Blogs')),
  },
  {
    path: '/GioiThieus',
    permission: '',
    title: 'GioiThieus',
    name: 'GioiThieus',
    icon: 'cloud',
    showInMenu: true,
    component: LoadableComponent(() => import('../../scenes/GioiThieus')),
  },
  {
    path: '/Menus',
    permission: '',
    title: 'Menus',
    name: 'Menus',
    icon: 'menu',
    showInMenu: true,
    component: LoadableComponent(() => import('../../scenes/Menus')),
  },
  {
    path: '/LoaiSanPhams',
    permission: '',
    title: 'LoaiSanPhams',
    name: 'LoaiSanPhams',
    icon: 'euro',
    showInMenu: true,
    component: LoadableComponent(() => import('../../scenes/LoaiSanPhams')),
  },
  {
    path: '/LienHes',
    permission: '',
    title: 'LienHes',
    name: 'LienHes',
    icon: 'coffee',
    showInMenu: true,
    component: LoadableComponent(() => import('../../scenes/LienHes')),
  },
  {
    path: '/SanPhams',
    permission: '',
    title: 'SanPhams',
    name: 'SanPhams',
    icon: 'gift',
    showInMenu: true,
    component: LoadableComponent(() => import('../../scenes/SanPhams')),
  },
];

export const routers = [...userRouter, ...appRouters];
